// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: user.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	User_UsersCount_FullMethodName    = "/userpb.User/UsersCount"
	User_UserViewUsers_FullMethodName = "/userpb.User/UserViewUsers"
	User_UserViewUser_FullMethodName  = "/userpb.User/UserViewUser"
)

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserClient interface {
	UsersCount(ctx context.Context, in *UserView, opts ...grpc.CallOption) (*Usercount, error)
	UserViewUsers(ctx context.Context, in *UserView, opts ...grpc.CallOption) (*UserUsers, error)
	UserViewUser(ctx context.Context, in *UserView, opts ...grpc.CallOption) (*UserSignup, error)
}

type userClient struct {
	cc grpc.ClientConnInterface
}

func NewUserClient(cc grpc.ClientConnInterface) UserClient {
	return &userClient{cc}
}

func (c *userClient) UsersCount(ctx context.Context, in *UserView, opts ...grpc.CallOption) (*Usercount, error) {
	out := new(Usercount)
	err := c.cc.Invoke(ctx, User_UsersCount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UserViewUsers(ctx context.Context, in *UserView, opts ...grpc.CallOption) (*UserUsers, error) {
	out := new(UserUsers)
	err := c.cc.Invoke(ctx, User_UserViewUsers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UserViewUser(ctx context.Context, in *UserView, opts ...grpc.CallOption) (*UserSignup, error) {
	out := new(UserSignup)
	err := c.cc.Invoke(ctx, User_UserViewUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
// All implementations must embed UnimplementedUserServer
// for forward compatibility
type UserServer interface {
	UsersCount(context.Context, *UserView) (*Usercount, error)
	UserViewUsers(context.Context, *UserView) (*UserUsers, error)
	UserViewUser(context.Context, *UserView) (*UserSignup, error)
	mustEmbedUnimplementedUserServer()
}

// UnimplementedUserServer must be embedded to have forward compatible implementations.
type UnimplementedUserServer struct {
}

func (UnimplementedUserServer) UsersCount(context.Context, *UserView) (*Usercount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UsersCount not implemented")
}
func (UnimplementedUserServer) UserViewUsers(context.Context, *UserView) (*UserUsers, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserViewUsers not implemented")
}
func (UnimplementedUserServer) UserViewUser(context.Context, *UserView) (*UserSignup, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserViewUser not implemented")
}
func (UnimplementedUserServer) mustEmbedUnimplementedUserServer() {}

// UnsafeUserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServer will
// result in compilation errors.
type UnsafeUserServer interface {
	mustEmbedUnimplementedUserServer()
}

func RegisterUserServer(s grpc.ServiceRegistrar, srv UserServer) {
	s.RegisterService(&User_ServiceDesc, srv)
}

func _User_UsersCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserView)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UsersCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_UsersCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UsersCount(ctx, req.(*UserView))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UserViewUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserView)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UserViewUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_UserViewUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UserViewUsers(ctx, req.(*UserView))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UserViewUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserView)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UserViewUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_UserViewUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UserViewUser(ctx, req.(*UserView))
	}
	return interceptor(ctx, in, info, handler)
}

// User_ServiceDesc is the grpc.ServiceDesc for User service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var User_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "userpb.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UsersCount",
			Handler:    _User_UsersCount_Handler,
		},
		{
			MethodName: "UserViewUsers",
			Handler:    _User_UserViewUsers_Handler,
		},
		{
			MethodName: "UserViewUser",
			Handler:    _User_UserViewUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
